from __future__ import annotations

ENSEMBLE_RANKER_STRATEGY_KEY = "ensemble_ranker_v1"
ENSEMBLE_RANKER_RULE_NAME = "ensemble_ranker_weighted_vote_v1"

STAGE_OBSERVE = "observe"
STAGE_WEIGHT_READY = "weight_ready"
STAGE_ENSEMBLE_READY = "ensemble_ready"
ENSEMBLE_STAGES = frozenset({STAGE_OBSERVE, STAGE_WEIGHT_READY, STAGE_ENSEMBLE_READY})

SIGNAL_FACTOR_COMBO = "factor_combo"
SIGNAL_HIGH_WINRATE_COMBO = "high_winrate_combo"
SIGNAL_FACTOR_CANDIDATE = "factor_candidate"
SIGNAL_MODEL_FAMILY = "model_family"
SIGNAL_OTHER = "other"
MAJOR_SIGNAL_TYPES = (
    SIGNAL_FACTOR_COMBO,
    SIGNAL_HIGH_WINRATE_COMBO,
    SIGNAL_MODEL_FAMILY,
    SIGNAL_FACTOR_CANDIDATE,
)

LOW_SAMPLE_LIMIT = 50
WEIGHT_READY_SAMPLE_COUNT = 200
ENSEMBLE_READY_SAMPLE_COUNT = 500
WEIGHT_READY_MIN_DAYS = 20
ENSEMBLE_MIN_SETTLED_SAMPLES = 100
LOSS_STREAK_THRESHOLD = 5
RECENT_WINDOW_COUNT = 3
MIN_ENSEMBLE_CANDIDATES = 3
ENSEMBLE_MARGIN_THRESHOLD = 0.08
