from __future__ import annotations

from typing import Any

EXTERNAL_DATA_FACTORS: tuple[dict[str, Any], ...] = (
    {
        "name": "fvg_up_3",
        "category": "smc",
        "description": "三K向上公允价值缺口",
        "formula": "low > high.shift(2)",
        "source_file": "kline_advanced_features.py",
        "direction": "neutral",
    },
    {
        "name": "fvg_down_3",
        "category": "smc",
        "description": "三K向下公允价值缺口",
        "formula": "high < low.shift(2)",
        "source_file": "kline_advanced_features.py",
        "direction": "neutral",
    },
    {
        "name": "liquidity_sweep_high_20",
        "category": "smc",
        "description": "上方流动性扫单",
        "formula": "high > rolling_high(20).shift(1) and close < prior_high",
        "source_file": "kline_advanced_features.py",
        "direction": "neutral",
    },
    {
        "name": "liquidity_sweep_low_20",
        "category": "smc",
        "description": "下方流动性扫单",
        "formula": "low < rolling_low(20).shift(1) and close > prior_low",
        "source_file": "kline_advanced_features.py",
        "direction": "neutral",
    },
    {
        "name": "breakout_high_20",
        "category": "smc",
        "description": "20周期高点突破",
        "formula": "close > rolling_high(20).shift(1)",
        "source_file": "kline_advanced_features.py",
        "direction": "neutral",
    },
    {
        "name": "breakdown_low_20",
        "category": "smc",
        "description": "20周期低点跌破",
        "formula": "close < rolling_low(20).shift(1)",
        "source_file": "kline_advanced_features.py",
        "direction": "neutral",
    },
    {
        "name": "ret_autocorr_20",
        "category": "statistic",
        "description": "20周期收益自相关",
        "formula": "corr(ret_1, ret_1.shift(1), 20)",
        "source_file": "kline_advanced_features.py",
        "direction": "neutral",
    },
    {
        "name": "price_volume_corr_20",
        "category": "statistic",
        "description": "20周期价量相关",
        "formula": "corr(ret_1, vol_chg, 20)",
        "source_file": "kline_advanced_features.py",
        "direction": "neutral",
    },
    {
        "name": "vol_ret_corr_20",
        "category": "statistic",
        "description": "20周期量价联动",
        "formula": "corr(vol_chg, ret_1, 20)",
        "source_file": "kline_advanced_features.py",
        "direction": "neutral",
    },
    {
        "name": "rolling_sharpe_60",
        "category": "performance",
        "description": "60周期滚动夏普",
        "formula": "mean(ret_1,60) / std(ret_1,60) * sqrt(60)",
        "source_file": "kline_advanced_features.py",
        "direction": "higher_better",
    },
    {
        "name": "win_rate_60",
        "category": "performance",
        "description": "60周期上涨胜率",
        "formula": "mean(ret_1 > 0, 60)",
        "source_file": "kline_advanced_features.py",
        "direction": "higher_better",
    },
    {
        "name": "profit_factor_60",
        "category": "performance",
        "description": "60周期盈亏比",
        "formula": "sum(max(ret_1,0),60) / abs(sum(min(ret_1,0),60))",
        "source_file": "kline_advanced_features.py",
        "direction": "higher_better",
    },
    {
        "name": "open_interest_chg_1",
        "category": "positioning",
        "description": "持仓量变化率",
        "formula": "open_interest.pct_change(1)",
        "source_file": "external_factor_data.py",
        "direction": "neutral",
    },
    {
        "name": "open_interest_z_20",
        "category": "positioning",
        "description": "持仓量20周期Z分数",
        "formula": "(open_interest - mean(open_interest,20)) / std(open_interest,20)",
        "source_file": "external_factor_data.py",
        "direction": "neutral",
    },
    {
        "name": "long_short_ratio",
        "category": "positioning",
        "description": "全市场多空账户比",
        "formula": "long_account / short_account",
        "source_file": "external_factor_data.py",
        "direction": "neutral",
    },
    {
        "name": "long_short_ratio_chg_1",
        "category": "positioning",
        "description": "多空账户比变化率",
        "formula": "long_short_ratio.pct_change(1)",
        "source_file": "external_factor_data.py",
        "direction": "neutral",
    },
    {
        "name": "taker_buy_sell_ratio",
        "category": "taker_flow",
        "description": "主动买卖量比",
        "formula": "taker_buy_vol / taker_sell_vol",
        "source_file": "external_factor_data.py",
        "direction": "neutral",
    },
    {
        "name": "taker_buy_share",
        "category": "taker_flow",
        "description": "主动买入占比",
        "formula": "taker_buy_vol / (taker_buy_vol + taker_sell_vol)",
        "source_file": "external_factor_data.py",
        "direction": "neutral",
    },
    {
        "name": "fear_greed_value",
        "category": "sentiment",
        "description": "恐惧贪婪指数",
        "formula": "Alternative.me Fear & Greed Index",
        "source_file": "external_factor_data.py",
        "direction": "neutral",
    },
    {
        "name": "fear_greed_chg_1",
        "category": "sentiment",
        "description": "恐惧贪婪指数变化",
        "formula": "fear_greed_value.diff(1)",
        "source_file": "external_factor_data.py",
        "direction": "neutral",
    },
    {
        "name": "exchange_netflow_z_20",
        "category": "onchain",
        "description": "交易所净流入Z分数",
        "formula": "(exchange_netflow - mean(exchange_netflow,20)) / std(exchange_netflow,20)",
        "source_file": "external_factor_data.py",
        "direction": "neutral",
    },
    {
        "name": "active_addresses_chg_1",
        "category": "onchain",
        "description": "活跃地址变化率",
        "formula": "active_addresses.pct_change(1)",
        "source_file": "external_factor_data.py",
        "direction": "neutral",
    },
)
