from __future__ import annotations

from typing import Any

from app.services.factor_technical_extensions import TECHNICAL_INDICATOR_FACTORS

ADDITIONAL_FACTORS: tuple[dict[str, Any], ...] = (
    {
        "name": "log_ret_1",
        "category": "return",
        "description": "单周期对数收益率",
        "formula": "log(close / close.shift(1))",
        "direction": "neutral",
    },
    {
        "name": "ret_1_z_20",
        "category": "return",
        "description": "单周期收益率20周期Z分数",
        "formula": "(ret_1 - mean(ret_1,20)) / std(ret_1,20)",
        "direction": "neutral",
    },
    {
        "name": "downside_vol_20",
        "category": "volatility",
        "description": "20周期下行波动率",
        "formula": "std(min(ret_1, 0), 20)",
        "direction": "neutral",
    },
    {
        "name": "downside_vol_60",
        "category": "volatility",
        "description": "60周期下行波动率",
        "formula": "std(min(ret_1, 0), 60)",
        "direction": "neutral",
    },
    {
        "name": "upside_vol_20",
        "category": "volatility",
        "description": "20周期上行波动率",
        "formula": "std(max(ret_1, 0), 20)",
        "direction": "neutral",
    },
    {
        "name": "upside_vol_60",
        "category": "volatility",
        "description": "60周期上行波动率",
        "formula": "std(max(ret_1, 0), 60)",
        "direction": "neutral",
    },
    {
        "name": "vol_of_vol_20",
        "category": "volatility",
        "description": "20周期波动率的波动率",
        "formula": "std(vol_std_20, 20)",
        "direction": "neutral",
    },
    {
        "name": "realized_skew_20",
        "category": "volatility",
        "description": "20周期已实现偏度",
        "formula": "skew(ret_1, 20)",
        "direction": "neutral",
    },
    {
        "name": "realized_kurt_20",
        "category": "volatility",
        "description": "20周期已实现峰度",
        "formula": "kurt(ret_1, 20)",
        "direction": "neutral",
    },
    {
        "name": "range_ma_20",
        "category": "volatility",
        "description": "20周期高低价振幅均值",
        "formula": "mean(hl_range, 20)",
        "direction": "neutral",
    },
    {
        "name": "range_z_20",
        "category": "volatility",
        "description": "高低价振幅20周期Z分数",
        "formula": "(hl_range - mean(hl_range,20)) / std(hl_range,20)",
        "direction": "neutral",
    },
    {
        "name": "ema_ratio_12",
        "category": "moving_average",
        "description": "12周期EMA偏离",
        "formula": "close / ema(12) - 1",
        "direction": "neutral",
    },
    {
        "name": "ema_ratio_26",
        "category": "moving_average",
        "description": "26周期EMA偏离",
        "formula": "close / ema(26) - 1",
        "direction": "neutral",
    },
    {
        "name": "sma_slope_20",
        "category": "moving_average",
        "description": "20周期均线斜率",
        "formula": "sma(20).pct_change(3)",
        "direction": "neutral",
    },
    {
        "name": "sma_slope_60",
        "category": "moving_average",
        "description": "60周期均线斜率",
        "formula": "sma(60).pct_change(3)",
        "direction": "neutral",
    },
    {
        "name": "rsi_7",
        "category": "momentum",
        "description": "RSI（7周期）",
        "formula": "RSI(7)",
        "direction": "neutral",
    },
    {
        "name": "rsi_21",
        "category": "momentum",
        "description": "RSI（21周期）",
        "formula": "RSI(21)",
        "direction": "neutral",
    },
    {
        "name": "roc_12",
        "category": "momentum",
        "description": "12周期变化率",
        "formula": "close.pct_change(12)",
        "direction": "neutral",
    },
    {
        "name": "ppo_12_26",
        "category": "momentum",
        "description": "价格百分比振荡器（12/26）",
        "formula": "ema(12) / ema(26) - 1",
        "direction": "neutral",
    },
    {
        "name": "stochastic_k_14",
        "category": "momentum",
        "description": "随机指标K值（14周期）",
        "formula": "100 * (close - low_14) / (high_14 - low_14)",
        "direction": "neutral",
    },
    {
        "name": "stochastic_d_3",
        "category": "momentum",
        "description": "随机指标D值（3周期平滑）",
        "formula": "mean(stochastic_k_14, 3)",
        "direction": "neutral",
    },
    {
        "name": "williams_r_14",
        "category": "momentum",
        "description": "Williams %R（14周期）",
        "formula": "-100 * (high_14 - close) / (high_14 - low_14)",
        "direction": "neutral",
    },
    {
        "name": "cci_20",
        "category": "momentum",
        "description": "CCI商品通道指数（20周期）",
        "formula": "(typical - sma(typical,20)) / (0.015 * mean_abs_dev)",
        "direction": "neutral",
    },
    {
        "name": "volume_z_20",
        "category": "volume",
        "description": "成交量20周期Z分数",
        "formula": "(volume - mean(volume,20)) / std(volume,20)",
        "direction": "neutral",
    },
    {
        "name": "dollar_volume_ma_20",
        "category": "volume",
        "description": "20周期成交额均值",
        "formula": "mean(close * volume, 20)",
        "direction": "neutral",
    },
    {
        "name": "mfi_14",
        "category": "volume",
        "description": "资金流量指标MFI（14周期）",
        "formula": "100 - 100 / (1 + positive_money_flow / negative_money_flow)",
        "direction": "neutral",
    },
    {
        "name": "cmf_20",
        "category": "volume",
        "description": "Chaikin资金流（20周期）",
        "formula": "sum(money_flow_volume,20) / sum(volume,20)",
        "direction": "neutral",
    },
    {
        "name": "obv_slope_20",
        "category": "volume",
        "description": "OBV 20周期斜率",
        "formula": "OBV.diff(20) / sum(volume,20)",
        "direction": "neutral",
    },
    {
        "name": "body_to_range",
        "category": "structure",
        "description": "实体占振幅比例",
        "formula": "(close - open) / (high - low)",
        "direction": "neutral",
    },
    {
        "name": "gap_1",
        "category": "structure",
        "description": "开盘相对上一收盘跳空",
        "formula": "open / close.shift(1) - 1",
        "direction": "neutral",
    },
    {
        "name": "close_to_high_20",
        "category": "structure",
        "description": "收盘价距20周期高点",
        "formula": "close / rolling_high(20) - 1",
        "direction": "neutral",
    },
    {
        "name": "close_to_low_20",
        "category": "structure",
        "description": "收盘价距20周期低点",
        "formula": "close / rolling_low(20) - 1",
        "direction": "neutral",
    },
)

ADDITIONAL_FACTORS = (*ADDITIONAL_FACTORS, *TECHNICAL_INDICATOR_FACTORS)
