from __future__ import annotations

from typing import Any

TECHNICAL_INDICATOR_FACTORS: tuple[dict[str, Any], ...] = (
    {
        "name": "aroon_up_25",
        "category": "momentum",
        "description": "Aroon Up（25周期）",
        "formula": "100 * (25 - periods_since_high(25)) / 25",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "aroon_down_25",
        "category": "momentum",
        "description": "Aroon Down（25周期）",
        "formula": "100 * (25 - periods_since_low(25)) / 25",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "aroon_osc_25",
        "category": "momentum",
        "description": "Aroon振荡器（25周期）",
        "formula": "aroon_up_25 - aroon_down_25",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "dmi_spread_14",
        "category": "momentum",
        "description": "DMI方向差（14周期）",
        "formula": "+DI(14) - -DI(14)",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "keltner_width_20",
        "category": "volatility",
        "description": "肯特纳通道宽度（20周期）",
        "formula": "4 * ATR(10) / EMA(20)",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "keltner_pos_20",
        "category": "structure",
        "description": "肯特纳通道位置（20周期）",
        "formula": "(close - EMA(20)) / (2 * ATR(10))",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "trix_15",
        "category": "momentum",
        "description": "TRIX三重指数动量（15周期）",
        "formula": "pct_change(EMA(EMA(EMA(close,15),15),15))",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "tsi_25_13",
        "category": "momentum",
        "description": "真实强弱指数TSI（25/13）",
        "formula": "100 * double_ema(momentum,25,13) / double_ema(abs(momentum),25,13)",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "ultimate_osc_7_14_28",
        "category": "momentum",
        "description": "终极振荡器（7/14/28）",
        "formula": "100 * (4 * avg7 + 2 * avg14 + avg28) / 7",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "vortex_pos_14",
        "category": "momentum",
        "description": "Vortex正向趋势（14周期）",
        "formula": "sum(abs(high - low.shift(1)),14) / sum(true_range,14)",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "vortex_neg_14",
        "category": "momentum",
        "description": "Vortex负向趋势（14周期）",
        "formula": "sum(abs(low - high.shift(1)),14) / sum(true_range,14)",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "vortex_spread_14",
        "category": "momentum",
        "description": "Vortex趋势差（14周期）",
        "formula": "vortex_pos_14 - vortex_neg_14",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "mass_index_25",
        "category": "volatility",
        "description": "Mass Index区间扩张（25周期）",
        "formula": "sum(ema(high-low,9) / ema(ema(high-low,9),9), 25)",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "ulcer_index_14",
        "category": "volatility",
        "description": "Ulcer下行回撤风险（14周期）",
        "formula": "sqrt(mean(((close - max(close,14)) / max(close,14) * 100)^2,14))",
        "source_file": "kline_technical_indicators.py",
        "direction": "lower_better",
    },
    {
        "name": "cmo_14",
        "category": "momentum",
        "description": "Chande动量振荡器（14周期）",
        "formula": "100 * (sum(gains,14) - sum(losses,14)) / (sum(gains,14) + sum(losses,14))",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "coppock_10_14_11",
        "category": "momentum",
        "description": "Coppock曲线（10/14/11）",
        "formula": "wma(roc(11) + roc(14), 10)",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "kst_10_15_20_30",
        "category": "momentum",
        "description": "KST综合动量",
        "formula": "sma(roc10,10) + 2*sma(roc15,10) + 3*sma(roc20,10) + 4*sma(roc30,15)",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "kst_signal_9",
        "category": "momentum",
        "description": "KST信号线（9周期）",
        "formula": "sma(kst_10_15_20_30, 9)",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "kst_diff",
        "category": "momentum",
        "description": "KST动量差",
        "formula": "kst_10_15_20_30 - kst_signal_9",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "force_index_13",
        "category": "volume",
        "description": "Force Index量价力度（13周期）",
        "formula": "ema((close - close.shift(1)) * volume, 13)",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "emv_14",
        "category": "volume",
        "description": "Ease of Movement价量推动（14周期）",
        "formula": "sma(midpoint.diff() / ((volume / 100000000) / (high - low)), 14)",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "chaikin_osc_3_10",
        "category": "volume",
        "description": "Chaikin资金流振荡器（3/10）",
        "formula": "ema(adl,3) - ema(adl,10)",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "adl_slope_20",
        "category": "volume",
        "description": "ADL累积分布斜率（20周期）",
        "formula": "adl.diff(20) / sum(volume,20)",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "pvt_slope_20",
        "category": "volume",
        "description": "PVT价量趋势斜率（20周期）",
        "formula": "pvt.diff(20) / sum(volume,20)",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "pvo_12_26",
        "category": "volume",
        "description": "成交量百分比振荡器（12/26）",
        "formula": "ema(volume,12) / ema(volume,26) - 1",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "vwma_ratio_20",
        "category": "volume",
        "description": "VWMA成交量加权均线偏离（20周期）",
        "formula": "close / (sum(close*volume,20) / sum(volume,20)) - 1",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
    {
        "name": "bop_14",
        "category": "structure",
        "description": "Balance of Power多空实体力度（14周期）",
        "formula": "sma((close - open) / (high - low), 14)",
        "source_file": "kline_technical_indicators.py",
        "direction": "neutral",
    },
)
